language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-robotype' ]; then cd .. && eval "mv $currentfolder generator-robotype" && cd generator-robotype; fi

